version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: boarddb
      MYSQL_USER: yash
      MYSQL_PASSWORD: yash123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./board-backend
    container_name: board-backend
    restart: always
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/boarddb
      SPRING_DATASOURCE_USERNAME: yash
      SPRING_DATASOURCE_PASSWORD: yash123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"

  frontend:
    build: ./board-frontend
    container_name: board-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8080

volumes:
  mysql_data:
